import { Platform, StyleSheet } from 'react-native';

import { FtColors, FtSurfaces } from '@/constants/fasttable';

export const adminCardShadow =
  Platform.OS === 'ios'
    ? { shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.2, shadowRadius: 8 }
    : { elevation: 4 };

export const adminStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: FtColors.background },
  boot: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: FtColors.background },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 18, paddingBottom: 100 },
  loader: { marginVertical: 16 },
  hero: { marginBottom: 16 },
  backRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 10 },
  backText: { fontSize: 15, fontWeight: '600', color: FtColors.accentText },
  heroEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: FtColors.accentMuted,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  heroTitle: { fontSize: 26, fontWeight: '800', color: FtColors.text, marginTop: 4 },
  heroSub: { fontSize: 14, color: FtColors.textMuted, marginTop: 8, lineHeight: 20 },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: FtColors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: FtColors.border,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, paddingVertical: 13, fontSize: 15, color: FtColors.text },
  searchClear: { padding: 4 },
  filterRow: { gap: 8, marginBottom: 16, paddingRight: 4 },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: FtColors.border,
    backgroundColor: FtColors.surface,
  },
  filterChipOn: { borderColor: FtColors.accent, backgroundColor: FtColors.surfaceElevated },
  filterChipText: { fontSize: 12, color: FtColors.textMuted, fontWeight: '600' },
  filterChipTextOn: { color: FtColors.accentText, fontWeight: '700' },
  muted: { color: FtColors.textMuted, marginBottom: 12, fontSize: 14 },
  errText: { color: FtColors.danger, fontSize: 14, lineHeight: 20 },
  emptyCard: {
    padding: 24,
    borderRadius: 16,
    backgroundColor: FtColors.surfaceElevated,
    borderWidth: 1,
    borderColor: FtColors.border,
    marginBottom: 14,
    alignItems: 'center',
    gap: 8,
  },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: FtColors.text },
  emptySub: { fontSize: 13, color: FtColors.textMuted, textAlign: 'center' },
  card: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: FtColors.surfaceElevated,
    borderWidth: 1,
    borderColor: FtColors.borderSubtle,
    marginBottom: 12,
  },
  cardTitle: { fontSize: 17, fontWeight: '800', color: FtColors.text },
  cardSub: { fontSize: 13, color: FtColors.textMuted, marginTop: 6 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  estadoTag: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  estadoTagText: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  cardActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  btnIcon: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: FtColors.border,
    backgroundColor: FtColors.surface,
  },
  btnIconDanger: { borderColor: FtSurfaces.dangerBorder },
  btnIconText: { fontWeight: '700', color: FtColors.text, fontSize: 14 },
  btnIconTextDanger: { color: FtColors.danger },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 28,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: FtColors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    ...adminCardShadow,
  },
  hubCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 18,
    borderRadius: 18,
    backgroundColor: FtColors.surfaceElevated,
    borderWidth: 1,
    borderColor: FtColors.borderSubtle,
    marginBottom: 12,
  },
  hubIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: FtColors.surface,
    borderWidth: 1,
    borderColor: FtColors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubMeta: { flex: 1 },
  hubTitle: { fontSize: 17, fontWeight: '800', color: FtColors.text },
  hubSub: { fontSize: 13, color: FtColors.textMuted, marginTop: 4, lineHeight: 18 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: FtSurfaces.overlay,
    justifyContent: 'flex-end',
  },
  modalBackdropCenter: {
    flex: 1,
    backgroundColor: FtSurfaces.overlay,
    justifyContent: 'center',
    padding: 24,
  },
  modalSheet: {
    maxHeight: '92%',
    backgroundColor: FtColors.surfaceElevated,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: FtColors.border,
  },
  modalBox: {
    backgroundColor: FtColors.surfaceElevated,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: FtColors.border,
    maxHeight: '90%',
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: FtColors.border,
    alignSelf: 'center',
    marginBottom: 14,
  },
  modalTitle: { fontSize: 18, fontWeight: '800', color: FtColors.text },
  modalSub: { fontSize: 14, color: FtColors.textMuted, marginTop: 6 },
  modalLabel: {
    fontSize: 12,
    color: FtColors.textFaint,
    marginTop: 14,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  input: {
    borderWidth: 1,
    borderColor: FtColors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: FtColors.text,
    fontSize: 16,
    backgroundColor: FtColors.surface,
  },
  inputMultiline: { minHeight: 80, textAlignVertical: 'top' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: FtColors.border,
    backgroundColor: FtColors.surface,
  },
  chipOn: { borderColor: FtColors.accent, backgroundColor: FtColors.surfaceElevated },
  chipText: { fontSize: 13, color: FtColors.textMuted, fontWeight: '600' },
  chipTextOn: { color: FtColors.accentText, fontWeight: '700' },
  modalOk: {
    marginTop: 18,
    backgroundColor: FtColors.accent,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalOkOff: { opacity: 0.6 },
  modalOkText: { fontWeight: '800', color: FtColors.onAccent },
  modalCancel: { textAlign: 'center', marginTop: 14, color: FtColors.accentText, fontWeight: '600', paddingBottom: 8 },
  recipeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: FtColors.surface,
    borderWidth: 1,
    borderColor: FtColors.borderSubtle,
  },
  recipeName: { flex: 1, fontSize: 14, fontWeight: '700', color: FtColors.text },
  recipeQty: { width: 72 },
  recipeRemove: { padding: 6 },
  addIngBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: FtColors.accent,
  },
  addIngBtnText: { color: FtColors.accentText, fontWeight: '700' },
  dishThumb: { width: 56, height: 56, borderRadius: 12, backgroundColor: FtColors.surface },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: FtColors.borderSubtle,
  },
  pickerRowText: { flex: 1, fontSize: 15, color: FtColors.text, fontWeight: '600' },
  pickerRowSub: { fontSize: 12, color: FtColors.textMuted, marginTop: 2 },
});

export function estadoMesaStyle(estado: 'libre' | 'ocupada' | 'reservada') {
  switch (estado) {
    case 'libre':
      return {
        bg: FtSurfaces.successBadge,
        color: FtColors.success,
        label: 'Libre',
      };
    case 'ocupada':
      return {
        bg: FtSurfaces.dangerBadge,
        color: FtColors.danger,
        label: 'Ocupada',
      };
    case 'reservada':
      return {
        bg: FtSurfaces.warningBadge,
        color: FtColors.warning,
        label: 'Reservada',
      };
    default:
      return { bg: FtColors.surface, color: FtColors.textMuted, label: estado };
  }
}
